import Head from 'next/head'
import Image from 'next/image'

const Logo = () => (
  <>
    <img src="/logoFerrarezziSis.png" width={150} className="p-2 hidden md:inline-block" alt="logo" />
    <img src="/logoFerrarezziSisHz.png" width={100} className="p-2 md:hidden" alt="logo" />
  </>
)

const Menu = () => (
  <div className='p-2 flex items-center'>
    <a href="https://github.com/rdFerrarezi" target="_blank" rel="noopener noreferrer">
      github
    </a>
    <a href="https://instagram.com/rodrigoferrarezzi" target="_blank" rel="noopener noreferrer">
      instagram
    </a>
    <a href="https://www.youtube.com/channel/UCvIm95EbndZpEnCaQ6i1i6Q" target="_blank" rel="noopener noreferrer">
      youtube
    </a>
  </div>
)

const Banner = () => (
  <div className='container max-w-5xl m-auto p-6 flex-1 flex flex-col justify-center items-center sm:items-start text-center sm:text-left'>
    <span className='text-gray'>Criamos a FerrarezziSis para te colocar on-line</span>
    <div className="uppercase text-4xl font-extrabold leading-snug">
      Desenvolver <span className='text-green'>soluções</span> inteligentes
    </div>
    <span className='text-gray'>Tornando o seu negócio muito mais competitivo.</span>
  </div>
)

const Header = () => (
  <div className='p-2 container max-w-5xl m-auto flex justify-between items-center'>
    <Logo />
    <Menu/>
  </div>
)

export default function Home() {
  return (
    <div className="flex flex-col flex-1 "
        style={{ background: 'url(https://images.pexels.com/photos/3184325/pexels-photo-3184325.jpeg?auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260) no-repeat center/cover' }}
    >
      <Head>
        <title>Landing Page NextJS with TailwindCSS</title>

        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Banner />
    </div>
  )
}
